//! Remote component-library packages — module-path classification, the
//! `nemo.lock` lockfile, and the `.nemo/packages` cache layout.
//!
//! This module is **pure** (no git/network): it owns the filesystem-and-string
//! parts of the Go-style package model. The actual fetch (git) lives in the
//! `nemo` binary's `get` command, which shells out to the `git` CLI — so no VCS
//! crate dependency is needed and none leaks into `nemo-config`.
//!
//! A dependency is a **module path** (e.g. `github.com/geoffjay/nemo-components`)
//! mapped to a version; `nemo get` clones it into
//! `.nemo/packages/<module>@<version>/` and records the resolved commit in
//! `nemo.lock`. An `<import src="github.com/…">` then resolves against that cache.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// The lockfile name at a project root.
pub const LOCKFILE: &str = "nemo.lock";

/// Classifies an import `src` as a remote **module path** rather than a local
/// filesystem path.
///
/// A module path has a host-like first segment (contains a `.`, e.g.
/// `github.com`) followed by at least one more `/`-separated segment, and does
/// **not** begin with `./`, `../`, or `/`. This keeps a bare local file like
/// `foo.nemo` (a single dotted segment) or `components/card.nemo` (no dotted
/// host) on the local path; callers should still prefer an existing local file
/// when one is present.
pub fn is_module_path(src: &str) -> bool {
    if src.starts_with("./") || src.starts_with("../") || src.starts_with('/') {
        return false;
    }
    // A Windows absolute path (`C:\…`) or drive-relative path is local.
    if src.len() >= 2 && src.as_bytes()[1] == b':' {
        return false;
    }
    let mut segments = src.split('/');
    let first = segments.next().unwrap_or("");
    first.contains('.') && segments.next().is_some()
}

/// The package cache directory for a project root (`<root>/.nemo/packages`).
pub fn packages_dir(root: &Path) -> PathBuf {
    root.join(".nemo").join("packages")
}

/// The cache directory for one module at one version
/// (`<root>/.nemo/packages/<module>@<version>`). The module path's own `/`
/// separators become nested directories; the `@<version>` suffix lands on the
/// final segment.
pub fn package_dir(root: &Path, module: &str, version: &str) -> PathBuf {
    packages_dir(root).join(format!("{module}@{version}"))
}

/// One pinned dependency in [`Lockfile`].
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct LockedPackage {
    /// Module path (e.g. `github.com/geoffjay/nemo-components`).
    pub module: String,
    /// Requested version / tag (e.g. `v1.2.0`).
    pub version: String,
    /// Resolved commit hash the fetch pinned.
    pub commit: String,
}

/// The `nemo.lock` lockfile: resolved commits for each dependency, pinning a
/// reproducible build (Go's `go.sum` / `Cargo.lock` role).
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize, Serialize)]
pub struct Lockfile {
    /// Pinned packages, serialized as a TOML array of `[[package]]` tables.
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    /// Reads and parses a `nemo.lock`. Returns `Ok(default)` (empty) when the
    /// file is absent, so callers can treat "no lockfile" as "no pins".
    pub fn load(path: &Path) -> Result<Self, String> {
        match std::fs::read_to_string(path) {
            Ok(content) => toml::from_str(&content).map_err(|e| e.to_string()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(e.to_string()),
        }
    }

    /// Serializes to a deterministic TOML string (packages sorted by module).
    pub fn to_toml(&self) -> Result<String, String> {
        let mut sorted = self.clone();
        sorted.packages.sort_by(|a, b| a.module.cmp(&b.module));
        let body = toml::to_string_pretty(&sorted).map_err(|e| e.to_string())?;
        Ok(format!(
            "# Auto-generated by `nemo get`. Do not edit by hand.\n{body}"
        ))
    }

    /// Writes the lockfile to `path` (deterministically ordered).
    pub fn save(&self, path: &Path) -> Result<(), String> {
        std::fs::write(path, self.to_toml()?).map_err(|e| e.to_string())
    }

    /// Sets (or replaces) the pin for a module.
    pub fn set(&mut self, module: &str, version: &str, commit: &str) {
        self.packages.retain(|p| p.module != module);
        self.packages.push(LockedPackage {
            module: module.to_string(),
            version: version.to_string(),
            commit: commit.to_string(),
        });
    }

    /// The `module → version` map used to resolve module imports against the
    /// cache.
    pub fn versions(&self) -> BTreeMap<String, String> {
        self.packages
            .iter()
            .map(|p| (p.module.clone(), p.version.clone()))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_module_vs_local_paths() {
        assert!(is_module_path("github.com/geoffjay/nemo-components"));
        assert!(is_module_path("example.com/pkg"));
        // Local paths.
        assert!(!is_module_path("./components/card.nemo"));
        assert!(!is_module_path("../shared/x.nemo"));
        assert!(!is_module_path("/abs/x.nemo"));
        assert!(!is_module_path("foo.nemo")); // dotted but single segment
        assert!(!is_module_path("components/card.nemo")); // no dotted host
        assert!(!is_module_path("github.com")); // host only, no path
        assert!(!is_module_path("C:/x/y.nemo")); // windows drive
    }

    #[test]
    fn package_paths_nest_module_segments() {
        let root = Path::new("/proj");
        assert_eq!(packages_dir(root), Path::new("/proj/.nemo/packages"));
        assert_eq!(
            package_dir(root, "github.com/geoffjay/nemo-components", "v1.2.0"),
            Path::new("/proj/.nemo/packages/github.com/geoffjay/nemo-components@v1.2.0")
        );
    }

    #[test]
    fn lockfile_round_trips_deterministically() {
        let mut lock = Lockfile::default();
        lock.set("github.com/b/two", "v0.1.0", "bbb");
        lock.set("github.com/a/one", "v1.0.0", "aaa");
        // set() replaces on repeat.
        lock.set("github.com/a/one", "v1.1.0", "aaa2");

        let toml_str = lock.to_toml().unwrap();
        // Sorted by module → a/one before b/two, regardless of insertion order.
        assert!(toml_str.find("a/one").unwrap() < toml_str.find("b/two").unwrap());

        let back: Lockfile = toml::from_str(&toml_str).unwrap();
        assert_eq!(back.versions().get("github.com/a/one").unwrap(), "v1.1.0");
        assert_eq!(back.packages.len(), 2);
        // Re-serializing yields identical bytes (determinism).
        assert_eq!(back.to_toml().unwrap(), toml_str);
    }

    #[test]
    fn missing_lockfile_is_empty() {
        let lock = Lockfile::load(Path::new("/no/such/nemo.lock")).unwrap();
        assert!(lock.packages.is_empty());
    }
}
