[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.skills]
workspace = false
command = "npx"
args = [
  "skills",
  "add",
  "./skills",
  "-a",
  "claude-code",
  "-a",
  "opencode",
  "-a",
  "crush",
  "-y",
]
